eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: false
  client:
    enabled: true
    service-url:
      defaultZone: http://${HOS}:8761/eureka

skill:
  service:
    url: it-is-local
